"""migration initiale

Revision ID: 980d7fecd9fa
Revises: 
Create Date: 2026-09-12 14:39:02.948787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980d7fecd9fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('article_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=True),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_title', sa.Enum('MANUTENTIONNAIRE', 'PRODUCTEUR', 'SUPERVISEUR', 'ADMINISTRATEUR', name='job_title_enum'), nullable=False),
    sa.Column('department', sa.Enum('PRODUCTION', 'LOGISTIQUE', 'RH', 'IT', 'ADMINISTRATION', name='department_enum'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['app_schema.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='app_schema'
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('machine_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('ordre_fabrication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_article', sa.Integer(), nullable=False),
    sa.Column('id_machine', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('capacities', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='ordre_fabrication_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('of_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id_article'], ['app_schema.articles.id'], ),
    sa.ForeignKeyConstraint(['id_machine'], ['app_schema.machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('materials_of',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('id_of', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['app_schema.materials.id'], ),
    sa.ForeignKeyConstraint(['id_of'], ['app_schema.ordre_fabrication.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_manager', sa.Integer(), nullable=False),
    sa.Column('id_of', sa.Integer(), nullable=False),
    sa.Column('press_ref', sa.String(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_employee'], ['app_schema.employees.id'], ),
    sa.ForeignKeyConstraint(['id_manager'], ['app_schema.employees.id'], ),
    sa.ForeignKeyConstraint(['id_of'], ['app_schema.ordre_fabrication.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('logistics_support_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED', name='request_status_enum'), nullable=False),
    sa.Column('id_handler_employee', sa.Integer(), nullable=True),
    sa.Column('taken_in_charge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_handler_employee'], ['app_schema.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_post'], ['app_schema.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('maintenance_requests',
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED', name='request_status_enum'), nullable=False),
    sa.Column('id_handler_employee', sa.Integer(), nullable=True),
    sa.Column('taken_in_charge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_handler_employee'], ['app_schema.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_post'], ['app_schema.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('post_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacities', sa.Integer(), nullable=True),
    sa.Column('qty_goods', sa.Integer(), nullable=True),
    sa.Column('qty_bads', sa.Integer(), nullable=True),
    sa.Column('bads_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['app_schema.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_post', 'recorded_at', name='uq_post_hours_post_recorded_at'),
    schema='app_schema'
    )
    op.create_table('post_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('stop_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['app_schema.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('production_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.Enum('OPERATOR', 'TECHNICIAN', name='comment_author_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_post'], ['app_schema.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('quality_support_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED', name='request_status_enum'), nullable=False),
    sa.Column('id_handler_employee', sa.Integer(), nullable=True),
    sa.Column('taken_in_charge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_handler_employee'], ['app_schema.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_post'], ['app_schema.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('supply_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'URGENT', 'RUPTURE', name='supply_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED', name='request_status_enum'), nullable=False),
    sa.Column('id_handler_employee', sa.Integer(), nullable=True),
    sa.Column('taken_in_charge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_handler_employee'], ['app_schema.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_material'], ['app_schema.materials.id'], ),
    sa.ForeignKeyConstraint(['id_post'], ['app_schema.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply_requests', schema='app_schema')
    op.drop_table('quality_support_requests', schema='app_schema')
    op.drop_table('production_comments', schema='app_schema')
    op.drop_table('post_stops', schema='app_schema')
    op.drop_table('post_hours', schema='app_schema')
    op.drop_table('maintenance_requests', schema='app_schema')
    op.drop_table('logistics_support_requests', schema='app_schema')
    op.drop_table('posts', schema='app_schema')
    op.drop_table('materials_of', schema='app_schema')
    op.drop_table('ordre_fabrication', schema='app_schema')
    op.drop_table('materials', schema='app_schema')
    op.drop_table('machines', schema='app_schema')
    op.drop_table('employees', schema='app_schema')
    op.drop_table('articles', schema='app_schema')
    # ### end Alembic commands ###
