"""migration initiale

Revision ID: f075ed3e6f6f
Revises: 
Create Date: 2026-09-12 14:39:11.616708
Revision date: 
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f075ed3e6f6f'  # pylint: disable=C0103
down_revision: Union[str, Sequence[str], None] = None  # pylint: disable=C0103
branch_labels: Union[str, Sequence[str], None] = None  # pylint: disable=C0103
depends_on: Union[str, Sequence[str], None] = None  # pylint: disable=C0103


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment="Identifiant unique de l'utilisateur"),
    sa.Column('username', sa.String(), nullable=False, comment="Nom d'utilisateur"),
    sa.Column('email', sa.String(), nullable=False, comment="Adresse email de l'utilisateur"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Utilisateur actif ?'),
    sa.Column('nb_failed_logins', sa.Integer(), nullable=False, comment='Nombre de tentatives de connexion échouées'),
    sa.Column('is_locked', sa.Boolean(), nullable=False, comment="Compte de l'utilisateur verrouillé ?"),
    sa.Column('permissions', sa.String(), nullable=False, comment="Permissions de l'utilisateur"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'utilisateur"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment="Date de dernière MàJ de l'utilisateur"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='auth_schema'
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique de la session'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='Empreinte SHA-256 du jeton de session'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment="Identifiant de l'utilisateur associé"),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment="Date d'expiration absolue de la session"),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False, comment='Date de dernière activité de la session'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Date de révocation de la session'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Date de création de la session'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_schema_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='auth_schema')
    op.create_table('users_passwords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique du mot de passe'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment="Identifiant de l'utilisateur associé"),
    sa.Column('password_hash', sa.String(), nullable=False, comment="Hash du mot de passe de l'utilisateur"),
    sa.Column('from_date', sa.DateTime(), nullable=False, comment='Date de début de validité du mot de passe'),
    sa.Column('to_date', sa.DateTime(), nullable=True, comment='Date fin de validité du mot de passe'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création du mot de passe'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière MàJ du mot de passe'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_passwords', schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_user_sessions_user_id'), table_name='user_sessions', schema='auth_schema')
    op.drop_table('user_sessions', schema='auth_schema')
    op.drop_table('users', schema='auth_schema')
    # ### end Alembic commands ###
